import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BoardContextProvider from "../contexts/BoardContext";
import BoardList from "../components/BoardList";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Agile Task Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.board}>
        <BoardContextProvider>
          <BoardList />
        </BoardContextProvider>
      </div>
    </div>
  );
}
